version: '3'

services:

  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1111
    volumes:
      - ./dka-blog:/var/www/html/
    ports:
      - 8080:80
    working_dir: /var/www/html/

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:/var/www/html/
    working_dir: /var/www/html/
    command: composer install